using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PoQuiz.Models
{
    public class NbaAllStarGame
    {
        // The Id property should be marked as not mapped if it's auto-generated by the database
        // [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        [Key]
        public int Id { get; set; }

        public string Player { get; set; }

        public int Year { get; set; }

        //[Column("Team")]
        //public string AllStarTeam { get; set; } // Renamed to avoid conflict with TeamAbbreviation.

        public string Role { get; set; }

        public string MVP { get; set; }

        [Column("Team")] // This assumes the second "Team" header is actually meant to be "TeamAbbreviation".
        public string TeamAbbreviation { get; set; }
    }
}
